# https://github.com/Devidanson/markdownlint/blob/master/doc/Rules.md
MD013: false    # 1行内の文字長さ制限解除
MD022:          # 章最後の空白ゼロ
  lines_above: 0
  lines_below: 0
MD024:          # 章タイトルの直服禁止
  allow_different_nesting: true   # ただし、別の章なら可
MD031: false    # コードブロックの最後の空白判定なし
MD032: false    # リスト前後の空白判定なし
MD033:          # 指定したhtmlタグ以外は利用禁止
  allowed_elements:
    - ApiUrl
    - br
    - ColorSample
    - GreenBadge
    - span
    - TagList
MD038: false    # コードブロック内にスペース可
MD040: false    # コードブロックの言語指定強制を解除
