# GitHub Docs - https://docs.github.com/ja/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
name: Build and Deploy
on:
  # pushもしくはpull requestでworkflowを起動する
  # ただしmaster branchに対してのみ
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup node.js
      uses: actions/setup-node@v1

    - name: Install dependancies
      run: yarn install --frozen-lockfile

    - name: Build docs
      run: yarn run docs:build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: github-pages
